### PR TITLE
Mobile Display Bug Fix

### PR DESCRIPTION
**Pull request by audreyau**
added mobile view: vertically scaled banner image, centered and scaled logo, no split-screen

### CODE REVIEW

**Comment by nelsonni** [comment]
Several CSS properties are either not being overridden or not properly set within these new CSS updates, including the use of `position: webkit sticky` which is not valid:
image

**Comment by audreyau** [comment]
How can I view the other invalid CSS properties aside from `position: webkit sticky`?

**Comment by nelsonni** [comment]
The screenshot in my previous comment is from the [Firefox Developer Tools](https://developer.mozilla.org/en-US/docs/Tools) panel (in Chrome, its called [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/)). The only CSS property that I saw being flagged as invalid was that `position: webkit sticky`, but there are a bunch that are not being applied (any CSS property that is crossed out in my screenshot isn't actually be applied to the rendered page).

Also, it appears that the EPICLab logo is being centered in all conditions. The `left: 65%` property is never being applied; although this is definitely being caused by the use of `position: sticky`. Was there a reason that `position: fixed` wasn't sufficient for the logo?

**Comment by audreyau** [comment]
That's strange. On Chrome, the logo isn't centered unless the display window is minimized.
Screen Shot 2020-08-07 at 10 08 01 AM

I used `position: sticky` instead of `position: fixed` because `position: sticky` confines the logo to its parent element (the banner). If I left it as `position: fixed`, the logo image stays fixed on the screen and stays in the background of the split-screen for users with a narrow browser window:
Screen Shot 2020-08-07 at 10 13 40 AM

**Comment by audreyau** [comment]
Screen Shot 2020-08-07 at 10 18 31 AM
Screen Shot 2020-08-07 at 10 18 38 AM

It appears that the logo on Firefox opts to the mobile display

**Comment by nelsonni** [comment]
According to https://caniuse.com/#feat=css-sticky, the `position:sticky` property is fairly well supported on all browsers. Preventing the logo from overflowing outside of the banner is a good effect, so let's keep it.

I looked into the issue a bit further, and realized something. You have the `.logo` CSS class commented as being `/*mobile logo*/` and the `@media (min-device-height: 824px), (min-device-width: 800px).logo` CSS class commented as being `/*desktop logo*/`, but these classes are not exclusive. The `.logo` class is always applied, and only when the `min-device-height` or `min-device-width` values are less than or equal to their thresholds will the `@media (min-device-height: 824px), (min-device-width: 800px).logo` class be applied on top of the `.logo` class.

The culprit in this case is the `margin: auto` in the `.logo` class. If you override it in the `@media (min-device-height: 824px), (min-device-width: 800px).logo` class, by adding `margin: 0`, then the `left: 65%` will be respected.

**Comment by audreyau** [comment]
got it! Thank you!

**Comment by nelsonni** [comment]
Also, although repositioning the logo to the center works on Chrome when you shrink the browser window enough to reach the CSS `@media` query bounds, it doesn't appear to work on Firefox. I'm almost certain this is caused by using `min-device-width` instead of [`min-width`](https://caniuse.com/#feat=mdn-css_at-rules_media_width), since `device-width` queries are [_"deprecated/obsolete and should not be used"_](https://caniuse.com/#feat=mdn-css_at-rules_media_device-width).

**Pull request merged**
